---
exclude: "docs|node_modules|migrations|.tox"
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
        exclude: /README\.rst$|^docs/.*\.rst$
      - id: check-symlinks
      - id: check-xml
      - id: mixed-line-ending
        args: ["--fix=lf"]
      #- id: detect-private-key
  
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16  # Use the ref you want to point at
    hooks:
    - id: mdformat
      # Optionally add plugins
      additional_dependencies:
      - mdformat-gfm
      - mdformat-black
      - mdformat-myst

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.0.0
    hooks:
        - id: commitlint
          stages: [commit-msg]
          additional_dependencies: ['conventional-changelog-conventionalcommits']
          args: [--config, commitlint.yaml]
